import { jsx as _jsx, jsxs as _jsxs } from "react/jsx-runtime";
import { useState } from 'react';
import { triggerHaptic } from '../api';
import { Clock, X } from 'lucide-react';
export const ArticlesView = ({ articles }) => {
    const [selectedArticle, setSelectedArticle] = useState(null);
    return (_jsxs("div", { className: "space-y-4 max-w-md mx-auto pb-24 px-4 pt-2", children: [_jsxs("div", { children: [_jsx("h2", { className: "text-xl font-black text-white light:text-[#1d2939]", children: "Moliyaviy Bilimlar" }), _jsx("p", { className: "text-xs text-[#899098]", children: "Moliyaviy erkinlik va tejamkorlik maqolalari" })] }), _jsx("div", { className: "space-y-3", children: articles.map((art) => (_jsxs("div", { onClick: () => {
                        triggerHaptic('light');
                        setSelectedArticle(art);
                    }, className: "rounded-3xl bg-[#213040] light:bg-white border border-[#354454] light:border-[#eaecf0] overflow-hidden shadow-md cursor-pointer group active:scale-98 transition-all", children: [_jsxs("div", { className: "h-36 w-full overflow-hidden relative", children: [_jsx("img", { src: art.image_url, alt: art.title, className: "w-full h-full object-cover group-hover:scale-105 transition-transform duration-500" }), _jsx("span", { className: "absolute top-3 left-3 px-2.5 py-0.5 rounded-full text-[10px] font-black uppercase bg-black/60 backdrop-blur-md text-white", children: art.category })] }), _jsxs("div", { className: "p-4 space-y-2", children: [_jsxs("div", { className: "flex items-center gap-2 text-[11px] text-[#899098]", children: [_jsx(Clock, { className: "w-3.5 h-3.5" }), _jsx("span", { children: art.read_time }), _jsx("span", { children: "\u2022" }), _jsx("span", { children: art.date })] }), _jsx("h3", { className: "text-sm font-bold text-white light:text-[#1d2939] group-hover:text-[#29c184] transition-colors leading-snug", children: art.title }), _jsx("p", { className: "text-xs text-[#b6bfd0] light:text-[#475467] line-clamp-2", children: art.summary })] })] }, art.id))) }), selectedArticle && (_jsx("div", { className: "fixed inset-0 z-50 flex items-center justify-center bg-black/70 backdrop-blur-md p-4", children: _jsxs("div", { className: "w-full max-w-lg bg-[#19232e] light:bg-white rounded-3xl border border-[#354454] max-h-[90vh] overflow-y-auto flex flex-col shadow-2xl", children: [_jsxs("div", { className: "sticky top-0 z-10 p-4 bg-[#19232e]/90 light:bg-white/90 backdrop-blur-md border-b border-[#354454]/60 flex items-center justify-between", children: [_jsx("span", { className: "text-xs font-bold text-[#29c184] uppercase", children: selectedArticle.category }), _jsx("button", { onClick: () => setSelectedArticle(null), className: "w-8 h-8 rounded-full bg-[#213040] flex items-center justify-center text-[#899098] hover:text-white", children: _jsx(X, { className: "w-4 h-4" }) })] }), _jsxs("div", { className: "p-5 space-y-4", children: [_jsx("h2", { className: "text-xl font-black text-white light:text-[#1d2939] leading-snug", children: selectedArticle.title }), _jsx("div", { className: "rounded-2xl overflow-hidden h-48", children: _jsx("img", { src: selectedArticle.image_url, alt: selectedArticle.title, className: "w-full h-full object-cover" }) }), _jsx("div", { className: "text-xs text-[#b6bfd0] light:text-[#344054] leading-relaxed whitespace-pre-line space-y-3 font-medium", children: selectedArticle.content })] })] }) }))] }));
};
